processor_type: "simulation" # Possible values are: simulation, simulation_debug, cdaq_to_cdaq, and cdaq_to_nidaq
model_dir: "C:/Users/CasGr/Documents/Data/training_data_quick.pt"
input_indices: # It specifies the indices of the activation data array that will be considered as inputs
  - 0
  - 6
# electrode_effects:
#   #  amplification: [28.5] # It always has to be a list
#   clipping_value: None
#noise:
#  type: gaussian
#  variance: 0.65
waveform:
  plateau_length: 1
  slope_length: 0
