results_dir: "tmp/ring"
runs: 500
start_gap: 0.4
stop_gap: 0.00825
data:
  gap: 0.5
  load: false # If load is false, it generates a new dataset. If load is a path to the data, it loads it to the data
  sample_no: 5000
  split_percentages: # The data is divided into training, validation and test datasets respectively
    - 0.6 # Percentage of the data used for training
    - 0.2 # Percentage of the data used for validation
    - 0.2 # Percentage of the data used for test
  batch_size: 512
  worker_no: 0 # Rule of thumb, 4 per GPU
  pin_memory: True
accuracy:
  epochs: 500
  learning_rate: 0.005
  batch_size: 512
algorithm: !include defaults/algorithms/gd/ring.yaml
processor: !include defaults/processors/simulation.yaml
